# mypy.ini
[mypy]
python_version = 3.12
ignore_missing_imports = True
exclude = (
    tests/.*
)

[mypy-pytest.*]
ignore_missing_imports = True

# mypy.ini
[mypy]
python_version = 3.12
ignore_missing_imports = True
exclude = (
    tests/.*
)

[mypy-pytest.*]
ignore_missing_imports = True